### ISSUE TITLE
Some kind of offset between cursor and mapInfo

### ISSUE THREAD

**Issue by sigmaducc** [chantaman1/db-irowiki#9]
This image is from wiki [World Map](https://db.irowiki.org/db/world-map/). When showing map contents, `mapInfo` is always close to cursor and never moves out of viewport.

![image](https://github.com/chantaman1/db-irowiki/assets/88367002/d071415b-4b65-478b-a32e-614c6e3fb823)

When adding the same code in this project it somehow looks like this. I know there is some kind of offset that's getting counted that also adds horizontal scrolling which it shouldn't. I've looked at the code `/public/js/map/common.js/` -> `OnMouseMove` and I cannot figure it out. 

Apart from this `Maps` tab is done!~

![image](https://github.com/chantaman1/db-irowiki/assets/88367002/be519d54-e828-4d6a-952b-25a8cd1875ab)

**Comment by EdgarblauDev** [comment]
i'll give it a look this Wednesday

**Comment by EdgarblauDev** [comment]
solved in last PR.
